// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewApplyPolicyParams creates a new ApplyPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplyPolicyParams() *ApplyPolicyParams {
	return &ApplyPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplyPolicyParamsWithTimeout creates a new ApplyPolicyParams object
// with the ability to set a timeout on a request.
func NewApplyPolicyParamsWithTimeout(timeout time.Duration) *ApplyPolicyParams {
	return &ApplyPolicyParams{
		timeout: timeout,
	}
}

// NewApplyPolicyParamsWithContext creates a new ApplyPolicyParams object
// with the ability to set a context for a request.
func NewApplyPolicyParamsWithContext(ctx context.Context) *ApplyPolicyParams {
	return &ApplyPolicyParams{
		Context: ctx,
	}
}

// NewApplyPolicyParamsWithHTTPClient creates a new ApplyPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplyPolicyParamsWithHTTPClient(client *http.Client) *ApplyPolicyParams {
	return &ApplyPolicyParams{
		HTTPClient: client,
	}
}

/*
ApplyPolicyParams contains all the parameters to send to the API endpoint

	for the apply policy operation.

	Typically these are written to a http.Request.
*/
type ApplyPolicyParams struct {

	/* Body.

	   Policy application details
	*/
	Body *models.ApplyPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apply policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyPolicyParams) WithDefaults() *ApplyPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apply policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apply policy params
func (o *ApplyPolicyParams) WithTimeout(timeout time.Duration) *ApplyPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply policy params
func (o *ApplyPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply policy params
func (o *ApplyPolicyParams) WithContext(ctx context.Context) *ApplyPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply policy params
func (o *ApplyPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply policy params
func (o *ApplyPolicyParams) WithHTTPClient(client *http.Client) *ApplyPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply policy params
func (o *ApplyPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the apply policy params
func (o *ApplyPolicyParams) WithBody(body *models.ApplyPolicyRequest) *ApplyPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the apply policy params
func (o *ApplyPolicyParams) SetBody(body *models.ApplyPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
