// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPolicyAuditTrailParams creates a new GetPolicyAuditTrailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPolicyAuditTrailParams() *GetPolicyAuditTrailParams {
	return &GetPolicyAuditTrailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPolicyAuditTrailParamsWithTimeout creates a new GetPolicyAuditTrailParams object
// with the ability to set a timeout on a request.
func NewGetPolicyAuditTrailParamsWithTimeout(timeout time.Duration) *GetPolicyAuditTrailParams {
	return &GetPolicyAuditTrailParams{
		timeout: timeout,
	}
}

// NewGetPolicyAuditTrailParamsWithContext creates a new GetPolicyAuditTrailParams object
// with the ability to set a context for a request.
func NewGetPolicyAuditTrailParamsWithContext(ctx context.Context) *GetPolicyAuditTrailParams {
	return &GetPolicyAuditTrailParams{
		Context: ctx,
	}
}

// NewGetPolicyAuditTrailParamsWithHTTPClient creates a new GetPolicyAuditTrailParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPolicyAuditTrailParamsWithHTTPClient(client *http.Client) *GetPolicyAuditTrailParams {
	return &GetPolicyAuditTrailParams{
		HTTPClient: client,
	}
}

/*
GetPolicyAuditTrailParams contains all the parameters to send to the API endpoint

	for the get policy audit trail operation.

	Typically these are written to a http.Request.
*/
type GetPolicyAuditTrailParams struct {

	/* ID.

	   UUID of the policy to get audit trail for
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get policy audit trail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyAuditTrailParams) WithDefaults() *GetPolicyAuditTrailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get policy audit trail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyAuditTrailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) WithTimeout(timeout time.Duration) *GetPolicyAuditTrailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) WithContext(ctx context.Context) *GetPolicyAuditTrailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) WithHTTPClient(client *http.Client) *GetPolicyAuditTrailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) WithID(id string) *GetPolicyAuditTrailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get policy audit trail params
func (o *GetPolicyAuditTrailParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPolicyAuditTrailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
