// Code generated by go-swagger; DO NOT EDIT.

package workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateWorkflowParams creates a new CreateWorkflowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateWorkflowParams() *CreateWorkflowParams {
	return &CreateWorkflowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWorkflowParamsWithTimeout creates a new CreateWorkflowParams object
// with the ability to set a timeout on a request.
func NewCreateWorkflowParamsWithTimeout(timeout time.Duration) *CreateWorkflowParams {
	return &CreateWorkflowParams{
		timeout: timeout,
	}
}

// NewCreateWorkflowParamsWithContext creates a new CreateWorkflowParams object
// with the ability to set a context for a request.
func NewCreateWorkflowParamsWithContext(ctx context.Context) *CreateWorkflowParams {
	return &CreateWorkflowParams{
		Context: ctx,
	}
}

// NewCreateWorkflowParamsWithHTTPClient creates a new CreateWorkflowParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateWorkflowParamsWithHTTPClient(client *http.Client) *CreateWorkflowParams {
	return &CreateWorkflowParams{
		HTTPClient: client,
	}
}

/*
CreateWorkflowParams contains all the parameters to send to the API endpoint

	for the create workflow operation.

	Typically these are written to a http.Request.
*/
type CreateWorkflowParams struct {

	/* Body.

	   Workflow definition in raw format
	*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create workflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkflowParams) WithDefaults() *CreateWorkflowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create workflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkflowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create workflow params
func (o *CreateWorkflowParams) WithTimeout(timeout time.Duration) *CreateWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create workflow params
func (o *CreateWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create workflow params
func (o *CreateWorkflowParams) WithContext(ctx context.Context) *CreateWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create workflow params
func (o *CreateWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create workflow params
func (o *CreateWorkflowParams) WithHTTPClient(client *http.Client) *CreateWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create workflow params
func (o *CreateWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create workflow params
func (o *CreateWorkflowParams) WithBody(body string) *CreateWorkflowParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create workflow params
func (o *CreateWorkflowParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
