// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetValuesReader is a Reader for the GetValues structure.
type GetValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetValuesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetValuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/search/values] getValues", response, response.Code())
	}
}

// NewGetValuesOK creates a GetValuesOK with default headers values
func NewGetValuesOK() *GetValuesOK {
	return &GetValuesOK{}
}

/*
GetValuesOK describes a response with status code 200, with default header values.

GetValuesOK get values o k
*/
type GetValuesOK struct {
	Payload *models.ValuesResponse
}

// IsSuccess returns true when this get values o k response has a 2xx status code
func (o *GetValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get values o k response has a 3xx status code
func (o *GetValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get values o k response has a 4xx status code
func (o *GetValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get values o k response has a 5xx status code
func (o *GetValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get values o k response a status code equal to that given
func (o *GetValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get values o k response
func (o *GetValuesOK) Code() int {
	return 200
}

func (o *GetValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesOK %s", 200, payload)
}

func (o *GetValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesOK %s", 200, payload)
}

func (o *GetValuesOK) GetPayload() *models.ValuesResponse {
	return o.Payload
}

func (o *GetValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValuesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetValuesBadRequest creates a GetValuesBadRequest with default headers values
func NewGetValuesBadRequest() *GetValuesBadRequest {
	return &GetValuesBadRequest{}
}

/*
GetValuesBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type GetValuesBadRequest struct {
	Payload *GetValuesBadRequestBody
}

// IsSuccess returns true when this get values bad request response has a 2xx status code
func (o *GetValuesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get values bad request response has a 3xx status code
func (o *GetValuesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get values bad request response has a 4xx status code
func (o *GetValuesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get values bad request response has a 5xx status code
func (o *GetValuesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get values bad request response a status code equal to that given
func (o *GetValuesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get values bad request response
func (o *GetValuesBadRequest) Code() int {
	return 400
}

func (o *GetValuesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesBadRequest %s", 400, payload)
}

func (o *GetValuesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesBadRequest %s", 400, payload)
}

func (o *GetValuesBadRequest) GetPayload() *GetValuesBadRequestBody {
	return o.Payload
}

func (o *GetValuesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetValuesBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetValuesInternalServerError creates a GetValuesInternalServerError with default headers values
func NewGetValuesInternalServerError() *GetValuesInternalServerError {
	return &GetValuesInternalServerError{}
}

/*
GetValuesInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type GetValuesInternalServerError struct {
	Payload *GetValuesInternalServerErrorBody
}

// IsSuccess returns true when this get values internal server error response has a 2xx status code
func (o *GetValuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get values internal server error response has a 3xx status code
func (o *GetValuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get values internal server error response has a 4xx status code
func (o *GetValuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get values internal server error response has a 5xx status code
func (o *GetValuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get values internal server error response a status code equal to that given
func (o *GetValuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get values internal server error response
func (o *GetValuesInternalServerError) Code() int {
	return 500
}

func (o *GetValuesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesInternalServerError %s", 500, payload)
}

func (o *GetValuesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/search/values][%d] getValuesInternalServerError %s", 500, payload)
}

func (o *GetValuesInternalServerError) GetPayload() *GetValuesInternalServerErrorBody {
	return o.Payload
}

func (o *GetValuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetValuesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetValuesBadRequestBody get values bad request body
swagger:model GetValuesBadRequestBody
*/
type GetValuesBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get values bad request body
func (o *GetValuesBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get values bad request body based on context it is used
func (o *GetValuesBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetValuesBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetValuesBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetValuesBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetValuesInternalServerErrorBody get values internal server error body
swagger:model GetValuesInternalServerErrorBody
*/
type GetValuesInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get values internal server error body
func (o *GetValuesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get values internal server error body based on context it is used
func (o *GetValuesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetValuesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetValuesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetValuesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
