// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewGetDiscoveryParams creates a new GetDiscoveryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDiscoveryParams() *GetDiscoveryParams {
	return &GetDiscoveryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDiscoveryParamsWithTimeout creates a new GetDiscoveryParams object
// with the ability to set a timeout on a request.
func NewGetDiscoveryParamsWithTimeout(timeout time.Duration) *GetDiscoveryParams {
	return &GetDiscoveryParams{
		timeout: timeout,
	}
}

// NewGetDiscoveryParamsWithContext creates a new GetDiscoveryParams object
// with the ability to set a context for a request.
func NewGetDiscoveryParamsWithContext(ctx context.Context) *GetDiscoveryParams {
	return &GetDiscoveryParams{
		Context: ctx,
	}
}

// NewGetDiscoveryParamsWithHTTPClient creates a new GetDiscoveryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDiscoveryParamsWithHTTPClient(client *http.Client) *GetDiscoveryParams {
	return &GetDiscoveryParams{
		HTTPClient: client,
	}
}

/*
GetDiscoveryParams contains all the parameters to send to the API endpoint

	for the get discovery operation.

	Typically these are written to a http.Request.
*/
type GetDiscoveryParams struct {

	/* Body.

	   Discovery request
	*/
	Body *models.DiscoveryRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get discovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDiscoveryParams) WithDefaults() *GetDiscoveryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get discovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDiscoveryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get discovery params
func (o *GetDiscoveryParams) WithTimeout(timeout time.Duration) *GetDiscoveryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get discovery params
func (o *GetDiscoveryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get discovery params
func (o *GetDiscoveryParams) WithContext(ctx context.Context) *GetDiscoveryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get discovery params
func (o *GetDiscoveryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get discovery params
func (o *GetDiscoveryParams) WithHTTPClient(client *http.Client) *GetDiscoveryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get discovery params
func (o *GetDiscoveryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get discovery params
func (o *GetDiscoveryParams) WithBody(body *models.DiscoveryRequest) *GetDiscoveryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get discovery params
func (o *GetDiscoveryParams) SetBody(body *models.DiscoveryRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetDiscoveryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
