// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnMetadata conn metadata
//
// swagger:model ConnMetadata
type ConnMetadata struct {

	// backend ID
	BackendID string `json:"BackendID,omitempty"`

	// client ID
	ClientID string `json:"ClientID,omitempty"`
}

// Validate validates this conn metadata
func (m *ConnMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conn metadata based on context it is used
func (m *ConnMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnMetadata) UnmarshalBinary(b []byte) error {
	var res ConnMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
