// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAPIKeyResponse create Api key response
//
// swagger:model CreateApiKeyResponse
type CreateAPIKeyResponse struct {

	// The generated API key token (secret). Store this securely.
	APIKey string `json:"apiKey,omitempty"`

	// The UUID of the created API key resource.
	ID string `json:"id,omitempty"`
}

// Validate validates this create Api key response
func (m *CreateAPIKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create Api key response based on context it is used
func (m *CreateAPIKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateAPIKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAPIKeyResponse) UnmarshalBinary(b []byte) error {
	var res CreateAPIKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
