// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateOrUpdateLogsPipelineConfigRequest CreateOrUpdateLogsPipelineConfigRequest defines the request structure for creating or updating a logs pipeline configuration
//
// swagger:model CreateOrUpdateLogsPipelineConfigRequest
type CreateOrUpdateLogsPipelineConfigRequest struct {

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this create or update logs pipeline config request
func (m *CreateOrUpdateLogsPipelineConfigRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create or update logs pipeline config request based on context it is used
func (m *CreateOrUpdateLogsPipelineConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateOrUpdateLogsPipelineConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateOrUpdateLogsPipelineConfigRequest) UnmarshalBinary(b []byte) error {
	var res CreateOrUpdateLogsPipelineConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
