// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreatePolicyRequest create policy request
//
// swagger:model CreatePolicyRequest
type CreatePolicyRequest struct {

	// Optional claim role for the policy.
	ClaimRole string `json:"claimRole,omitempty"`

	// Optional description for the policy.
	Description string `json:"description,omitempty"`

	// Name of the policy.
	// Required: true
	Name *string `json:"name"`

	// data scope
	DataScope *DataScope `json:"dataScope,omitempty"`

	// role
	Role RoleMap `json:"role,omitempty"`
}

// Validate validates this create policy request
func (m *CreatePolicyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDataScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatePolicyRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CreatePolicyRequest) validateDataScope(formats strfmt.Registry) error {
	if swag.IsZero(m.DataScope) { // not required
		return nil
	}

	if m.DataScope != nil {
		if err := m.DataScope.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dataScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dataScope")
			}
			return err
		}
	}

	return nil
}

func (m *CreatePolicyRequest) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(m.Role) { // not required
		return nil
	}

	if m.Role != nil {
		if err := m.Role.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create policy request based on the context it is used
func (m *CreatePolicyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDataScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatePolicyRequest) contextValidateDataScope(ctx context.Context, formats strfmt.Registry) error {

	if m.DataScope != nil {

		if swag.IsZero(m.DataScope) { // not required
			return nil
		}

		if err := m.DataScope.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dataScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dataScope")
			}
			return err
		}
	}

	return nil
}

func (m *CreatePolicyRequest) contextValidateRole(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Role) { // not required
		return nil
	}

	if err := m.Role.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("role")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("role")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreatePolicyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePolicyRequest) UnmarshalBinary(b []byte) error {
	var res CreatePolicyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
