// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KeyItem key item
//
// swagger:model KeyItem
type KeyItem struct {

	// description
	Description string `json:"description,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// key type
	KeyType string `json:"keyType,omitempty"`
}

// Validate validates this key item
func (m *KeyItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this key item based on context it is used
func (m *KeyItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KeyItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeyItem) UnmarshalBinary(b []byte) error {
	var res KeyItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
