// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsKeysResponse metrics keys response
//
// swagger:model MetricsKeysResponse
type MetricsKeysResponse struct {

	// IsLimitReached indicates whether the query limit was reached.
	IsLimitReached bool `json:"isLimitReached,omitempty"`

	// Keys is the list of metric keys.
	Keys []string `json:"keys"`

	// Name is the metric name.
	Name string `json:"name,omitempty"`
}

// Validate validates this metrics keys response
func (m *MetricsKeysResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics keys response based on context it is used
func (m *MetricsKeysResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsKeysResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsKeysResponse) UnmarshalBinary(b []byte) error {
	var res MetricsKeysResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
