// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsValuesResponse metrics values response
//
// swagger:model MetricsValuesResponse
type MetricsValuesResponse struct {

	// is limit reached
	IsLimitReached bool `json:"isLimitReached,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// values
	Values []string `json:"values"`
}

// Validate validates this metrics values response
func (m *MetricsValuesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics values response based on context it is used
func (m *MetricsValuesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsValuesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsValuesResponse) UnmarshalBinary(b []byte) error {
	var res MetricsValuesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
