// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Op op
//
// swagger:model Op
type Op string

// Validate validates this op
func (m Op) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this op based on context it is used
func (m Op) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
