// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Processor processor
//
// swagger:model Processor
type Processor struct {

	// args
	Args []string `json:"args"`

	// op
	Op string `json:"op,omitempty"`
}

// Validate validates this processor
func (m *Processor) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this processor based on context it is used
func (m *Processor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Processor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Processor) UnmarshalBinary(b []byte) error {
	var res Processor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
