// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateServiceAccountRequest update service account request
//
// swagger:model UpdateServiceAccountRequest
type UpdateServiceAccountRequest struct {

	// The new email address for the service account (optional).
	Email string `json:"email,omitempty"`

	// override policies
	OverridePolicies bool `json:"overridePolicies,omitempty"`

	// A list of policy UUIDs to set for the service account (optional, replaces existing). Provide empty list to remove all.
	PolicyUUIDs []string `json:"policyUUIDs"`

	// The UUID of the service account to update.
	// Required: true
	ServiceAccountID *string `json:"serviceAccountId"`
}

// Validate validates this update service account request
func (m *UpdateServiceAccountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceAccountID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateServiceAccountRequest) validateServiceAccountID(formats strfmt.Registry) error {

	if err := validate.Required("serviceAccountId", "body", m.ServiceAccountID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update service account request based on context it is used
func (m *UpdateServiceAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res UpdateServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
