// Code generated by go-swagger; DO NOT EDIT.

package k8s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewClustersListParams creates a new ClustersListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClustersListParams() *ClustersListParams {
	return &ClustersListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClustersListParamsWithTimeout creates a new ClustersListParams object
// with the ability to set a timeout on a request.
func NewClustersListParamsWithTimeout(timeout time.Duration) *ClustersListParams {
	return &ClustersListParams{
		timeout: timeout,
	}
}

// NewClustersListParamsWithContext creates a new ClustersListParams object
// with the ability to set a context for a request.
func NewClustersListParamsWithContext(ctx context.Context) *ClustersListParams {
	return &ClustersListParams{
		Context: ctx,
	}
}

// NewClustersListParamsWithHTTPClient creates a new ClustersListParams object
// with the ability to set a custom HTTPClient for a request.
func NewClustersListParamsWithHTTPClient(client *http.Client) *ClustersListParams {
	return &ClustersListParams{
		HTTPClient: client,
	}
}

/*
ClustersListParams contains all the parameters to send to the API endpoint

	for the clusters list operation.

	Typically these are written to a http.Request.
*/
type ClustersListParams struct {

	/* Body.

	     Request body for listing clusters.
	Contains source filters to apply.
	*/
	Body *models.ClustersListRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the clusters list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClustersListParams) WithDefaults() *ClustersListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the clusters list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClustersListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the clusters list params
func (o *ClustersListParams) WithTimeout(timeout time.Duration) *ClustersListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the clusters list params
func (o *ClustersListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the clusters list params
func (o *ClustersListParams) WithContext(ctx context.Context) *ClustersListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the clusters list params
func (o *ClustersListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the clusters list params
func (o *ClustersListParams) WithHTTPClient(client *http.Client) *ClustersListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the clusters list params
func (o *ClustersListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the clusters list params
func (o *ClustersListParams) WithBody(body *models.ClustersListRequest) *ClustersListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the clusters list params
func (o *ClustersListParams) SetBody(body *models.ClustersListRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ClustersListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
