// Code generated by go-swagger; DO NOT EDIT.

package ingestionkeys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewCreateIngestionKeyParams creates a new CreateIngestionKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateIngestionKeyParams() *CreateIngestionKeyParams {
	return &CreateIngestionKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateIngestionKeyParamsWithTimeout creates a new CreateIngestionKeyParams object
// with the ability to set a timeout on a request.
func NewCreateIngestionKeyParamsWithTimeout(timeout time.Duration) *CreateIngestionKeyParams {
	return &CreateIngestionKeyParams{
		timeout: timeout,
	}
}

// NewCreateIngestionKeyParamsWithContext creates a new CreateIngestionKeyParams object
// with the ability to set a context for a request.
func NewCreateIngestionKeyParamsWithContext(ctx context.Context) *CreateIngestionKeyParams {
	return &CreateIngestionKeyParams{
		Context: ctx,
	}
}

// NewCreateIngestionKeyParamsWithHTTPClient creates a new CreateIngestionKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateIngestionKeyParamsWithHTTPClient(client *http.Client) *CreateIngestionKeyParams {
	return &CreateIngestionKeyParams{
		HTTPClient: client,
	}
}

/*
CreateIngestionKeyParams contains all the parameters to send to the API endpoint

	for the create ingestion key operation.

	Typically these are written to a http.Request.
*/
type CreateIngestionKeyParams struct {

	/* Body.

	   Ingestion key creation information
	*/
	Body *models.CreateIngestionKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create ingestion key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIngestionKeyParams) WithDefaults() *CreateIngestionKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create ingestion key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIngestionKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create ingestion key params
func (o *CreateIngestionKeyParams) WithTimeout(timeout time.Duration) *CreateIngestionKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create ingestion key params
func (o *CreateIngestionKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create ingestion key params
func (o *CreateIngestionKeyParams) WithContext(ctx context.Context) *CreateIngestionKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create ingestion key params
func (o *CreateIngestionKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create ingestion key params
func (o *CreateIngestionKeyParams) WithHTTPClient(client *http.Client) *CreateIngestionKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create ingestion key params
func (o *CreateIngestionKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create ingestion key params
func (o *CreateIngestionKeyParams) WithBody(body *models.CreateIngestionKeyRequest) *CreateIngestionKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create ingestion key params
func (o *CreateIngestionKeyParams) SetBody(body *models.CreateIngestionKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateIngestionKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
