// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewCreateSilenceParams creates a new CreateSilenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSilenceParams() *CreateSilenceParams {
	return &CreateSilenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSilenceParamsWithTimeout creates a new CreateSilenceParams object
// with the ability to set a timeout on a request.
func NewCreateSilenceParamsWithTimeout(timeout time.Duration) *CreateSilenceParams {
	return &CreateSilenceParams{
		timeout: timeout,
	}
}

// NewCreateSilenceParamsWithContext creates a new CreateSilenceParams object
// with the ability to set a context for a request.
func NewCreateSilenceParamsWithContext(ctx context.Context) *CreateSilenceParams {
	return &CreateSilenceParams{
		Context: ctx,
	}
}

// NewCreateSilenceParamsWithHTTPClient creates a new CreateSilenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSilenceParamsWithHTTPClient(client *http.Client) *CreateSilenceParams {
	return &CreateSilenceParams{
		HTTPClient: client,
	}
}

/*
CreateSilenceParams contains all the parameters to send to the API endpoint

	for the create silence operation.

	Typically these are written to a http.Request.
*/
type CreateSilenceParams struct {

	/* Body.

	   Silence creation information
	*/
	Body *models.CreateSilenceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSilenceParams) WithDefaults() *CreateSilenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSilenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create silence params
func (o *CreateSilenceParams) WithTimeout(timeout time.Duration) *CreateSilenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create silence params
func (o *CreateSilenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create silence params
func (o *CreateSilenceParams) WithContext(ctx context.Context) *CreateSilenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create silence params
func (o *CreateSilenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create silence params
func (o *CreateSilenceParams) WithHTTPClient(client *http.Client) *CreateSilenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create silence params
func (o *CreateSilenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create silence params
func (o *CreateSilenceParams) WithBody(body *models.CreateSilenceRequest) *CreateSilenceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create silence params
func (o *CreateSilenceParams) SetBody(body *models.CreateSilenceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSilenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
