// Code generated by go-swagger; DO NOT EDIT.

package apikeys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListAPIKeysParams creates a new ListAPIKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListAPIKeysParams() *ListAPIKeysParams {
	return &ListAPIKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListAPIKeysParamsWithTimeout creates a new ListAPIKeysParams object
// with the ability to set a timeout on a request.
func NewListAPIKeysParamsWithTimeout(timeout time.Duration) *ListAPIKeysParams {
	return &ListAPIKeysParams{
		timeout: timeout,
	}
}

// NewListAPIKeysParamsWithContext creates a new ListAPIKeysParams object
// with the ability to set a context for a request.
func NewListAPIKeysParamsWithContext(ctx context.Context) *ListAPIKeysParams {
	return &ListAPIKeysParams{
		Context: ctx,
	}
}

// NewListAPIKeysParamsWithHTTPClient creates a new ListAPIKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewListAPIKeysParamsWithHTTPClient(client *http.Client) *ListAPIKeysParams {
	return &ListAPIKeysParams{
		HTTPClient: client,
	}
}

/*
ListAPIKeysParams contains all the parameters to send to the API endpoint

	for the list Api keys operation.

	Typically these are written to a http.Request.
*/
type ListAPIKeysParams struct {

	/* WithExpired.

	   Include expired API keys in the response.
	*/
	WithExpired *bool

	/* WithRevoked.

	   Include revoked API keys in the response.
	*/
	WithRevoked *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list Api keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAPIKeysParams) WithDefaults() *ListAPIKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list Api keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAPIKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list Api keys params
func (o *ListAPIKeysParams) WithTimeout(timeout time.Duration) *ListAPIKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list Api keys params
func (o *ListAPIKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list Api keys params
func (o *ListAPIKeysParams) WithContext(ctx context.Context) *ListAPIKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list Api keys params
func (o *ListAPIKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list Api keys params
func (o *ListAPIKeysParams) WithHTTPClient(client *http.Client) *ListAPIKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list Api keys params
func (o *ListAPIKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWithExpired adds the withExpired to the list Api keys params
func (o *ListAPIKeysParams) WithWithExpired(withExpired *bool) *ListAPIKeysParams {
	o.SetWithExpired(withExpired)
	return o
}

// SetWithExpired adds the withExpired to the list Api keys params
func (o *ListAPIKeysParams) SetWithExpired(withExpired *bool) {
	o.WithExpired = withExpired
}

// WithWithRevoked adds the withRevoked to the list Api keys params
func (o *ListAPIKeysParams) WithWithRevoked(withRevoked *bool) *ListAPIKeysParams {
	o.SetWithRevoked(withRevoked)
	return o
}

// SetWithRevoked adds the withRevoked to the list Api keys params
func (o *ListAPIKeysParams) SetWithRevoked(withRevoked *bool) {
	o.WithRevoked = withRevoked
}

// WriteToRequest writes these params to a swagger request
func (o *ListAPIKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.WithExpired != nil {

		// query param withExpired
		var qrWithExpired bool

		if o.WithExpired != nil {
			qrWithExpired = *o.WithExpired
		}
		qWithExpired := swag.FormatBool(qrWithExpired)
		if qWithExpired != "" {

			if err := r.SetQueryParam("withExpired", qWithExpired); err != nil {
				return err
			}
		}
	}

	if o.WithRevoked != nil {

		// query param withRevoked
		var qrWithRevoked bool

		if o.WithRevoked != nil {
			qrWithRevoked = *o.WithRevoked
		}
		qWithRevoked := swag.FormatBool(qrWithRevoked)
		if qWithRevoked != "" {

			if err := r.SetQueryParam("withRevoked", qWithRevoked); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
