// Code generated by go-swagger; DO NOT EDIT.

package apikeys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// ListAPIKeysReader is a Reader for the ListAPIKeys structure.
type ListAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAPIKeysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListAPIKeysInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/rbac/apikeys/list] listApiKeys", response, response.Code())
	}
}

// NewListAPIKeysOK creates a ListAPIKeysOK with default headers values
func NewListAPIKeysOK() *ListAPIKeysOK {
	return &ListAPIKeysOK{}
}

/*
ListAPIKeysOK describes a response with status code 200, with default header values.

ListAPIKeysOK list Api keys o k
*/
type ListAPIKeysOK struct {
	Payload []*models.ListAPIKeysResponseItem
}

// IsSuccess returns true when this list Api keys o k response has a 2xx status code
func (o *ListAPIKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Api keys o k response has a 3xx status code
func (o *ListAPIKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Api keys o k response has a 4xx status code
func (o *ListAPIKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Api keys o k response has a 5xx status code
func (o *ListAPIKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Api keys o k response a status code equal to that given
func (o *ListAPIKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Api keys o k response
func (o *ListAPIKeysOK) Code() int {
	return 200
}

func (o *ListAPIKeysOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysOK %s", 200, payload)
}

func (o *ListAPIKeysOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysOK %s", 200, payload)
}

func (o *ListAPIKeysOK) GetPayload() []*models.ListAPIKeysResponseItem {
	return o.Payload
}

func (o *ListAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPIKeysBadRequest creates a ListAPIKeysBadRequest with default headers values
func NewListAPIKeysBadRequest() *ListAPIKeysBadRequest {
	return &ListAPIKeysBadRequest{}
}

/*
ListAPIKeysBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type ListAPIKeysBadRequest struct {
	Payload *ListAPIKeysBadRequestBody
}

// IsSuccess returns true when this list Api keys bad request response has a 2xx status code
func (o *ListAPIKeysBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Api keys bad request response has a 3xx status code
func (o *ListAPIKeysBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Api keys bad request response has a 4xx status code
func (o *ListAPIKeysBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Api keys bad request response has a 5xx status code
func (o *ListAPIKeysBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list Api keys bad request response a status code equal to that given
func (o *ListAPIKeysBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list Api keys bad request response
func (o *ListAPIKeysBadRequest) Code() int {
	return 400
}

func (o *ListAPIKeysBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysBadRequest %s", 400, payload)
}

func (o *ListAPIKeysBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysBadRequest %s", 400, payload)
}

func (o *ListAPIKeysBadRequest) GetPayload() *ListAPIKeysBadRequestBody {
	return o.Payload
}

func (o *ListAPIKeysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListAPIKeysBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPIKeysInternalServerError creates a ListAPIKeysInternalServerError with default headers values
func NewListAPIKeysInternalServerError() *ListAPIKeysInternalServerError {
	return &ListAPIKeysInternalServerError{}
}

/*
ListAPIKeysInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type ListAPIKeysInternalServerError struct {
	Payload *ListAPIKeysInternalServerErrorBody
}

// IsSuccess returns true when this list Api keys internal server error response has a 2xx status code
func (o *ListAPIKeysInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Api keys internal server error response has a 3xx status code
func (o *ListAPIKeysInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Api keys internal server error response has a 4xx status code
func (o *ListAPIKeysInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Api keys internal server error response has a 5xx status code
func (o *ListAPIKeysInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list Api keys internal server error response a status code equal to that given
func (o *ListAPIKeysInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list Api keys internal server error response
func (o *ListAPIKeysInternalServerError) Code() int {
	return 500
}

func (o *ListAPIKeysInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysInternalServerError %s", 500, payload)
}

func (o *ListAPIKeysInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/rbac/apikeys/list][%d] listApiKeysInternalServerError %s", 500, payload)
}

func (o *ListAPIKeysInternalServerError) GetPayload() *ListAPIKeysInternalServerErrorBody {
	return o.Payload
}

func (o *ListAPIKeysInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListAPIKeysInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ListAPIKeysBadRequestBody list API keys bad request body
swagger:model ListAPIKeysBadRequestBody
*/
type ListAPIKeysBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this list API keys bad request body
func (o *ListAPIKeysBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list API keys bad request body based on context it is used
func (o *ListAPIKeysBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListAPIKeysBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListAPIKeysBadRequestBody) UnmarshalBinary(b []byte) error {
	var res ListAPIKeysBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ListAPIKeysInternalServerErrorBody list API keys internal server error body
swagger:model ListAPIKeysInternalServerErrorBody
*/
type ListAPIKeysInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this list API keys internal server error body
func (o *ListAPIKeysInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list API keys internal server error body based on context it is used
func (o *ListAPIKeysInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListAPIKeysInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListAPIKeysInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res ListAPIKeysInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
